/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/book_order_input`; params?: Router.UnknownInputParams; } | { pathname: `/cart`; params?: Router.UnknownInputParams; } | { pathname: `/course_items`; params?: Router.UnknownInputParams; } | { pathname: `/course_menu_item`; params?: Router.UnknownInputParams; } | { pathname: `/homedashboard`; params?: Router.UnknownInputParams; } | { pathname: `/kot_display`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/selectMemberDialog`; params?: Router.UnknownInputParams; } | { pathname: `/select_outlet`; params?: Router.UnknownInputParams; } | { pathname: `/splash`; params?: Router.UnknownInputParams; } | { pathname: `/order_details`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/data/courses`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/book_order_input`; params?: Router.UnknownOutputParams; } | { pathname: `/cart`; params?: Router.UnknownOutputParams; } | { pathname: `/course_items`; params?: Router.UnknownOutputParams; } | { pathname: `/course_menu_item`; params?: Router.UnknownOutputParams; } | { pathname: `/homedashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/kot_display`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/selectMemberDialog`; params?: Router.UnknownOutputParams; } | { pathname: `/select_outlet`; params?: Router.UnknownOutputParams; } | { pathname: `/splash`; params?: Router.UnknownOutputParams; } | { pathname: `/order_details`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/data/courses`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/book_order_input${`?${string}` | `#${string}` | ''}` | `/cart${`?${string}` | `#${string}` | ''}` | `/course_items${`?${string}` | `#${string}` | ''}` | `/course_menu_item${`?${string}` | `#${string}` | ''}` | `/homedashboard${`?${string}` | `#${string}` | ''}` | `/kot_display${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/selectMemberDialog${`?${string}` | `#${string}` | ''}` | `/select_outlet${`?${string}` | `#${string}` | ''}` | `/splash${`?${string}` | `#${string}` | ''}` | `/order_details${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/data/courses${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/book_order_input`; params?: Router.UnknownInputParams; } | { pathname: `/cart`; params?: Router.UnknownInputParams; } | { pathname: `/course_items`; params?: Router.UnknownInputParams; } | { pathname: `/course_menu_item`; params?: Router.UnknownInputParams; } | { pathname: `/homedashboard`; params?: Router.UnknownInputParams; } | { pathname: `/kot_display`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/selectMemberDialog`; params?: Router.UnknownInputParams; } | { pathname: `/select_outlet`; params?: Router.UnknownInputParams; } | { pathname: `/splash`; params?: Router.UnknownInputParams; } | { pathname: `/order_details`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/data/courses`; params?: Router.UnknownInputParams; };
    }
  }
}
